name: Snapshot Checker

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  snapshot-check-docker:
    runs-on: staking_test
    steps:
      - name: Run Snapshot Checker (Docker)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v /var/lib/docker/volumes:/var/lib/docker/volumes \
            -e EXECUTION_CLIENT='geth' \
            -e NETWORK=hoodi \
            ghcr.io/dappnode/staker-test-util/snapshot-checker:latest